//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuizBook
{
    using System;
    using System.Collections.Generic;
    
    public partial class AuditRecord
    {
        public AuditRecord()
        {
            this.AuditRecordFields = new HashSet<AuditRecordField>();
        }
    
        public int Id { get; set; }
        public string Action { get; set; }
        public string TableName { get; set; }
        public Nullable<int> TableKey { get; set; }
        public string UserName { get; set; }
        public System.DateTime AuditDate { get; set; }
    
        public virtual ICollection<AuditRecordField> AuditRecordFields { get; set; }
    }
}
