//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuizBook
{
    using System;
    using System.Collections.Generic;
    
    public partial class AuditTrailView
    {
        public string UserName { get; set; }
        public string Action { get; set; }
        public string TableName { get; set; }
        public string MemberName { get; set; }
        public string OldValue { get; set; }
        public string NewValue { get; set; }
        public System.DateTime AuditDate { get; set; }
    }
}
