//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuizBook
{
    using System;
    using System.Collections.Generic;
    
    public partial class BatchConfigurationTemp
    {
        public long Id { get; set; }
        public string GroupSelected { get; set; }
        public string SelectedID { get; set; }
        public string LoggedBy { get; set; }
        public Nullable<System.DateTime> DateLogged { get; set; }
    }
}
