//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuizBook
{
    using System;
    using System.Collections.Generic;
    
    public partial class BatchScopeContent
    {
        public long id { get; set; }
        public Nullable<long> BatchId { get; set; }
        public string BatchScope { get; set; }
        public string ScopeContentId { get; set; }
        public Nullable<long> QuestionTypeId { get; set; }
    
        public virtual T_Batch T_Batch { get; set; }
        public virtual T_QuestionType T_QuestionType { get; set; }
    }
}
