//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuizBook
{
    using System;
    using System.Collections.Generic;
    
    public partial class region_tab
    {
        public region_tab()
        {
            this.T_Candidate = new HashSet<T_Candidate>();
        }
    
        public int region_code { get; set; }
        public string region_name { get; set; }
        public int active { get; set; }
    
        public virtual ICollection<T_Candidate> T_Candidate { get; set; }
    }
}
