//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuizBook
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_BackGroundQuestAnswers
    {
        public long Id { get; set; }
        public Nullable<long> CandidateId { get; set; }
        public Nullable<long> BatchId { get; set; }
        public string Q1 { get; set; }
        public string Q2 { get; set; }
        public string Q3 { get; set; }
        public string Q4a { get; set; }
        public string Q4b { get; set; }
        public string Q5a { get; set; }
        public string Q5b { get; set; }
        public string Q6a { get; set; }
        public string Q6b { get; set; }
        public string Q7a { get; set; }
        public string Q7b { get; set; }
        public string Q8a { get; set; }
        public string Q8b { get; set; }
        public string Q9a { get; set; }
        public string Q9b { get; set; }
        public string Q10a { get; set; }
        public string Q10b { get; set; }
        public string Q11 { get; set; }
        public string Q12 { get; set; }
        public string Q13 { get; set; }
        public string Q14 { get; set; }
        public string Q15a { get; set; }
        public string Q15b { get; set; }
        public string Q15c { get; set; }
        public string Q16 { get; set; }
        public string Q17a { get; set; }
        public string Q17b { get; set; }
        public string Q18a { get; set; }
        public string Q18b { get; set; }
        public string Q19 { get; set; }
        public string Q20a { get; set; }
        public string Q20b { get; set; }
        public string Q21a { get; set; }
        public string Q21b { get; set; }
        public string Q22 { get; set; }
        public string Q23a1 { get; set; }
        public string Q23a2 { get; set; }
        public string Q23a3 { get; set; }
        public string Q23b1 { get; set; }
        public string Q23b2 { get; set; }
        public string Q23b3 { get; set; }
        public string Q24a1 { get; set; }
        public string Q24a2 { get; set; }
        public string Q24b { get; set; }
        public string Q25 { get; set; }
        public string Acknowledgement { get; set; }
        public Nullable<System.DateTime> Dateadded { get; set; }
    }
}
