//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuizBook
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_BatchQuestions
    {
        public long Id { get; set; }
        public Nullable<long> BatchId { get; set; }
        public Nullable<long> QuestionId { get; set; }
    
        public virtual T_Batch T_Batch { get; set; }
        public virtual T_BatchQuestions T_BatchQuestions1 { get; set; }
        public virtual T_BatchQuestions T_BatchQuestions2 { get; set; }
        public virtual T_Question T_Question { get; set; }
    }
}
