//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuizBook
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_BatchSet
    {
        public long Id { get; set; }
        public Nullable<long> CandidateId { get; set; }
        public Nullable<long> BatchId { get; set; }
        public Nullable<System.DateTime> TimeStarted { get; set; }
        public Nullable<bool> IsLive { get; set; }
        public Nullable<bool> Finished { get; set; }
        public Nullable<System.DateTime> LastActionTime { get; set; }
        public string LastActionDurationLeft { get; set; }
        public string TimeStartedRequestIP { get; set; }
        public Nullable<bool> TestGraded { get; set; }
        public Nullable<bool> Essay { get; set; }
        public Nullable<bool> Psychometric { get; set; }
        public string TestScore { get; set; }
    
        public virtual T_Batch T_Batch { get; set; }
        public virtual T_Candidate T_Candidate { get; set; }
    }
}
