//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuizBook
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_Batch
    {
        public T_Batch()
        {
            this.BatchScopeContents = new HashSet<BatchScopeContent>();
            this.T_BatchQuestions = new HashSet<T_BatchQuestions>();
            this.T_BatchSet = new HashSet<T_BatchSet>();
            this.T_CandidateAnswers = new HashSet<T_CandidateAnswers>();
            this.T_CandidateTemp = new HashSet<T_CandidateTemp>();
            this.T_CTestTracker = new HashSet<T_CTestTracker>();
            this.T_Reports = new HashSet<T_Reports>();
            this.T_Summary = new HashSet<T_Summary>();
            this.TestResultReports = new HashSet<TestResultReport>();
        }
    
        public long Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string BatchType { get; set; }
        public Nullable<bool> SessionOn { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public Nullable<int> Duration { get; set; }
        public Nullable<System.DateTime> DateAdded { get; set; }
        public Nullable<System.DateTime> DateModified { get; set; }
        public string AddedBy { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<long> TenantId { get; set; }
        public Nullable<decimal> CutOff { get; set; }
    
        public virtual ICollection<BatchScopeContent> BatchScopeContents { get; set; }
        public virtual ICollection<T_BatchQuestions> T_BatchQuestions { get; set; }
        public virtual ICollection<T_BatchSet> T_BatchSet { get; set; }
        public virtual ICollection<T_CandidateAnswers> T_CandidateAnswers { get; set; }
        public virtual ICollection<T_CandidateTemp> T_CandidateTemp { get; set; }
        public virtual ICollection<T_CTestTracker> T_CTestTracker { get; set; }
        public virtual ICollection<T_Reports> T_Reports { get; set; }
        public virtual ICollection<T_Summary> T_Summary { get; set; }
        public virtual Tenant Tenant { get; set; }
        public virtual ICollection<TestResultReport> TestResultReports { get; set; }
    }
}
