//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuizBook
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_Candidate
    {
        public T_Candidate()
        {
            this.T_BatchSet = new HashSet<T_BatchSet>();
            this.T_CandidateAnswers = new HashSet<T_CandidateAnswers>();
            this.T_CandidateTemp = new HashSet<T_CandidateTemp>();
            this.T_CTestTracker = new HashSet<T_CTestTracker>();
            this.T_Reports = new HashSet<T_Reports>();
            this.T_Summary = new HashSet<T_Summary>();
        }
    
        public long Id { get; set; }
        public string Code { get; set; }
        public string StaffID { get; set; }
        public string Grade { get; set; }
        public string Sector { get; set; }
        public string Division { get; set; }
        public Nullable<int> Branch { get; set; }
        public Nullable<int> Region { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string MaidenName { get; set; }
        public string MiddleName { get; set; }
        public string Sex { get; set; }
        public Nullable<System.DateTime> DateOfBirth { get; set; }
        public Nullable<long> Age { get; set; }
        public string Referer { get; set; }
        public string Passport { get; set; }
        public string Degree { get; set; }
        public string Course { get; set; }
        public string ClassOfDegree { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public string Email { get; set; }
        public string Comment { get; set; }
        public string RegisterBy { get; set; }
        public Nullable<System.DateTime> DateRegistered { get; set; }
        public string ApprovalStatus { get; set; }
        public string ApprovedBy { get; set; }
    
        public virtual branch_tab branch_tab { get; set; }
        public virtual division_tab division_tab { get; set; }
        public virtual grade_tab grade_tab { get; set; }
        public virtual region_tab region_tab { get; set; }
        public virtual sector_tab sector_tab { get; set; }
        public virtual ICollection<T_BatchSet> T_BatchSet { get; set; }
        public virtual ICollection<T_CandidateAnswers> T_CandidateAnswers { get; set; }
        public virtual ICollection<T_CandidateTemp> T_CandidateTemp { get; set; }
        public virtual ICollection<T_CTestTracker> T_CTestTracker { get; set; }
        public virtual ICollection<T_Reports> T_Reports { get; set; }
        public virtual ICollection<T_Summary> T_Summary { get; set; }
    }
}
