//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuizBook
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_CTestTracker
    {
        public long Id { get; set; }
        public Nullable<long> CandidateId { get; set; }
        public Nullable<long> BatchId { get; set; }
        public string CandidateCode { get; set; }
        public Nullable<long> LastQIndex { get; set; }
        public Nullable<System.DateTime> InitialStartTime { get; set; }
        public Nullable<System.DateTime> CurrentStartTime { get; set; }
        public string TestDuration { get; set; }
        public string RemainingDuration { get; set; }
        public Nullable<System.DateTime> EndTime { get; set; }
        public Nullable<bool> InSession { get; set; }
        public Nullable<bool> Finished { get; set; }
    
        public virtual T_Batch T_Batch { get; set; }
        public virtual T_Candidate T_Candidate { get; set; }
        public virtual Candidate Candidate { get; set; }
    }
}
