//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuizBook
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_Reports
    {
        public long ID { get; set; }
        public Nullable<long> BatchId { get; set; }
        public Nullable<long> CandidateId { get; set; }
        public Nullable<long> QuestionId { get; set; }
        public Nullable<long> Answer { get; set; }
        public Nullable<System.DateTime> TimeAnswered { get; set; }
        public Nullable<bool> Correct { get; set; }
        public Nullable<System.DateTime> TimeMarked { get; set; }
    
        public virtual T_Batch T_Batch { get; set; }
        public virtual T_Candidate T_Candidate { get; set; }
        public virtual T_Question T_Question { get; set; }
    }
}
