//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuizBook
{
    using System;
    using System.Collections.Generic;
    
    public partial class TestResultReport
    {
        public TestResultReport()
        {
            this.TestReportAnswers = new HashSet<TestReportAnswer>();
            this.TestReportSummaries = new HashSet<TestReportSummary>();
        }
    
        public long Id { get; set; }
        public string candidateId { get; set; }
        public Nullable<long> candId { get; set; }
        public string candidateName { get; set; }
        public Nullable<long> batchId { get; set; }
        public string batchName { get; set; }
        public string tenantName { get; set; }
        public Nullable<long> tenantId { get; set; }
        public string Correct { get; set; }
        public string Partial { get; set; }
        public string Wrong { get; set; }
        public string Unanswered { get; set; }
        public Nullable<decimal> percentage { get; set; }
        public string totalQuestionMark { get; set; }
        public string tstDate { get; set; }
        public string imgUrl { get; set; }
        public string fontUrl { get; set; }
        public Nullable<System.DateTime> dateInserted { get; set; }
    
        public virtual Candidate Candidate { get; set; }
        public virtual T_Batch T_Batch { get; set; }
        public virtual Tenant Tenant { get; set; }
        public virtual ICollection<TestReportAnswer> TestReportAnswers { get; set; }
        public virtual ICollection<TestReportSummary> TestReportSummaries { get; set; }
    }
}
