//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuizBook
{
    using System;
    using System.Collections.Generic;
    
    public partial class TestReportSummary
    {
        public long Id { get; set; }
        public Nullable<long> ReportId { get; set; }
        public Nullable<decimal> Correct { get; set; }
        public Nullable<decimal> Partial { get; set; }
        public Nullable<decimal> Wrong { get; set; }
        public Nullable<decimal> Unanswered { get; set; }
        public Nullable<decimal> CorrectPercent { get; set; }
        public Nullable<decimal> PartialPercent { get; set; }
        public Nullable<decimal> WrongPercent { get; set; }
        public Nullable<decimal> UnansweredPercent { get; set; }
        public Nullable<int> CorrectCount { get; set; }
        public Nullable<int> PartialCount { get; set; }
        public Nullable<int> WrongCount { get; set; }
        public Nullable<int> UnansweredCount { get; set; }
        public Nullable<int> questionCount { get; set; }
        public Nullable<decimal> questionTotalMark { get; set; }
        public Nullable<System.DateTime> testDate { get; set; }
    
        public virtual TestResultReport TestResultReport { get; set; }
    }
}
